### ISSUE TITLE
Pasting with backslashes instead of forward slashes

### ISSUE THREAD

**Issue by Tyree** [vladimir-tikhonov/tree-view-copy-relative-path#3]
When I paste the copied path, it has backslashes instead of forward slashes. Is there an option for this?

**Comment by vladimir-tikhonov** [comment]
It's really strange, copied path should always has backslashes. What OS are you using?

**Comment by Tyree** [comment]
I'm on Windows 7. On the video on the readme.md, it shows the path being pasted with forward-slashes, which is what we usually want in our code. But, for me, it pastes as backslashes (which come out as escapes) and I have to replace them all with forward-slashes.

**Comment by vladimir-tikhonov** [comment]
Thanks, I'll check on Windows

**Comment by seanpascoe** [comment]
> copied path should always has backslashes

you mean forward slashes?

yea, I have the same problem with the full and project paths. I'm guessing the command just pulls the path from the OS and since Windows uses backslashes, that's the result?

**Comment by divmonkey** [comment]
Same problem here. It should be forward slash "/" instead of backslash "\". I'm on Win10
my css rel path went  "..\assets\css\style.css".

**Comment by vladimir-tikhonov** [comment]
Fixed in version 1.0.1. I've added an option (enabled by default) that allows to replace backslashes with forward slashes
