### ISSUE TITLE
"copy relative path" command has no effect when no files are open

### ISSUE THREAD

**Issue by davidacreates** [vladimir-tikhonov/tree-view-copy-relative-path#7]
Atom: 1.18.0-beta0
OS: Sierra 10.12.4
Thrown From: tree-view-copy-relative-path package 1.1.0

I made a gif of what I am experiencing when I try to copy the relative path.

http://cloud.orangemooncreative.com/431j132t3O1T

**Comment by rscott78** [comment]
I'm also having this issue - it just started within the last day or two.

Atom: 1.17.0x64
OS: Windows 10

**Comment by slyy** [comment]
Same here :(

MacOS Sierra 10.12.3
Atom: 1.17.0
Package 1.1.0

**Comment by danielcaldas** [comment]
Same here. This happened after upgrading for atom 1.17.0  :/

**Comment by danielcaldas** [comment]
I took a look and it seems like something is wrong with **atom.workspace.getActivePaneItem()**
```coffeescript
copyRelativePath: (treeViewPath) ->
    return if not treeViewPath

    # Here, currentPath is giving undefined
    currentPath = atom.workspace.getActivePaneItem()?.buffer?.file?.path
    unless currentPath
      atom.notifications.addWarning '"Copy Relative Path" command
        has no effect when no files are open'
      return
```

**Comment by danielcaldas** [comment]
@orangemooncreative @rscott78 @slyy, for this to work properly just change:

```javascript
currentPath = atom.workspace.getActivePaneItem()?.buffer?.file?.path
```
to:
```javascript
currentPath = atom.workspace?.paneContainers?.center?.paneContainer?.activePane?.activeItem?.buffer?.file?.path
```

**Comment by vladimir-tikhonov** [comment]
Should be fixed in v1.2.0, could someone confirm please?

**Comment by danielcaldas** [comment]
@vladimir-tikhonov Just tried it. Works good for me with v1.2.0 :+1:

**Comment by davidacreates** [comment]
@vladimir-tikhonov  works great. thanks!
